/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

Result * findnumbers_100_svc(Data *argp, struct svc_req *rqstp) {
	static Result  result;
    result.min = -1;
    result.max = -1;

	 for(int i = argp->start; i <= argp->end; i++) {
        if(result.min == -1 || result.min > argp->v[i]) {
            result.min = argp->v[i];
        }
        if(result.max < argp->v[i] ){
            result.max = argp->v[i];
        }
    }

	return &result;
}
