/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULA_H_RPCGEN
#define _CALCULA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Result {
	float min;
	float max;
};
typedef struct Result Result;

struct Data {
	float v[500000];
	int start;
	int end;
};
typedef struct Data Data;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define findNumbers 1
extern  Result * findnumbers_100(Data *, CLIENT *);
extern  Result * findnumbers_100_svc(Data *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define findNumbers 1
extern  Result * findnumbers_100();
extern  Result * findnumbers_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Result (XDR *, Result*);
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Result ();
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULA_H_RPCGEN */
