/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcula.h"

bool_t
xdr_Result (XDR *xdrs, Result *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->v, 500000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->end))
		 return FALSE;
	return TRUE;
}
